### ISSUE TITLE
Editing on the computer

### ISSUE THREAD

**Issue by yentzee** [dxzl/akai-s950#1]
Hi,
first of all thanks a lot for doing this.
I am just waiting for my rs 232 cable to arrive.
I was wondering whether you can recommend a program that allows editing of the 12 bit files on the computer (doesnt matter if pc or mac) without altering the samples data except for the edits to then send it back. I just got a s950 for its nice sound but editing is a pain especially if mounted in a rack and not at 100% optimum height.
Really looking fwd to trying the beta. If this works this would be a huge improvement for the instrument which is gaining more and more in popularity due its nice sound when driving the opamps before the ad converters a bit.

cheers,
jens

**Comment by dxzl** [comment]
I hope things work out for you jens,
Best place to get my program is http://s900.yahcolorize.com/
Please email me directly at dxzl@live.com and let me know how things work.
- Scott S.
